### ISSUE TITLE
Exclude Admins from the maintenance mode

### ISSUE THREAD

**Issue by Epizefiri** [wp-cli/maintenance-mode-command#25]
Hi,
It would be great if the logged users and the wp-admin folder would be excluded from the maintenance.
As owner of the website I would like to navigate the website while the other users are blocked.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @Epizefiri !

This command simply interacts with WordPress core's bundled maintenance mode. For what you're describing, I'd recommend checking out the WordPress.org Plugins directory for a suitable plugin.
